import './globals.css'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'PapiHub',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <div className="bg-white">
        {children}
      </div>
      </body>
      </html>
  )
}
